
import toml
from pathlib import Path

def main():
    """
    This script reads the version from pyproject.toml and writes it into
    a new, untracked file: src/godforsaken_save_manager/_version.py
    """
    project_root = Path(__file__).parent.parent.parent
    pyproject_path = project_root / "pyproject.toml"
    version_file_path = project_root / "src" / "godforsaken_save_manager" / "_version.py"

    # Read version from pyproject.toml
    with open(pyproject_path, "r", encoding="utf-8") as f:
        data = toml.load(f)
    version = data["tool"]["poetry"]["version"]
    print(f"Found version {version} in {pyproject_path.name}")

    # Write to _version.py
    content = f'# This file is generated by docs/scripts/prepare_build.py\n__version__ = "{version}"\n'
    with open(version_file_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Successfully generated {version_file_path.name} with version {version}")

if __name__ == "__main__":
    main()
